# Minimal Mistakes
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default

# Site settings
title: iorate.github.io
name: iorate
description: iorate's site
url: https://iorate.github.io
repository: iorate/iorate.github.io
# google_site_verification:

# Site author
author:
  name : iorate
  bio : A graduate student
  location: Kyoto, Japan
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/iorate
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/iorate

# Site footer
footer:
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/iorate
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: https://twitter.com/iorate

# Reading files
include:
  - _pages

# Conversion and Markdown processing
markdown: kramdown

# Front Matter Defaults
defaults:
  - scope:
      path: _pages
      type: pages
    values:
      layout: single
      sidebar:
        nav: docs
      toc: true

# Plugins
plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache
